### ISSUE TITLE
Crash on rendering player

### ISSUE THREAD

**Issue by ZeClass** [Autovw/AdvancedNetherite#30]
**Describe the crash / error**
I equipped netherite emerald helmet (and netherite diamond when testing) and now whenever I open my inventory or go into third person, I crash.

**To Reproduce**
Equip any advanced netherite armor.
Open Inventory / Go into third person to render player.
Profit?

**Expected behavior**
I expect to not crash whenever my player's model is rendered/loaded.

**Logs**
https://pastebin.com/2PZnd6G4

**Technical Information (please complete the following information):**
- 1.19.2
- Fabric loader 0.14.21 and Fabric API 0.76.0
- 1.6.6 & 1.6.7 (tried with both)

**Comment by Autovw** [comment]
This particular issue is caused by other mods using poorly written mixins to change a feature that is already covered by Fabric API. There's nothing on my end that I can do about this.

The crashlog provided looks similar to the one from [this report](https://github.com/Autovw/AdvancedNetheriteFabric/issues/19). Both of these logs point to a mod called ``chime``.
You'd have to make a report to ``chime`` instead.
