### ISSUE TITLE
Tag Ingots as minecraft:ingots/netherite

### ISSUE THREAD

**Issue by Attack8** [Autovw/AdvancedNetherite#42]
**Is your feature request related to a problem? Please describe.**

See Creators-Of-Create/Create#6422

**Describe the solution you'd like**

As of Creators-Of-Create/Create#6464:
To provide compatibility with the Create diving suit, the AdvancedNetherite ingots must be taged as minecraft:ingots/netherite

**Comment by Autovw** [comment]
The reason ingots from this mod aren't tagged in forge:ingots/netherite is because that tag is used in the upgrade to Netherite-Iron recipes. So including them in said tag would "break" my recipes. 

Considering you're the author of the PR, my suggestion would be to check if the armor items are fire resistant (AKA don't burn when dropped in lava) instead.

**Comment by Attack8** [comment]
Ok, can do
